<<enz, fig=T, echo=F, results=hide, height=8, width=6>>=
par(mfrow=c(3,2), mar=c(3,5,4,.5))

var<-alldata$Respiration
cond<-is.na(var)==F
timeseries(alldata$Respiration[cond], alldata$days[cond], alldata$Litter[cond], pch=pch, pt.bg=colscale, type="o", endsig=T, main="Actual respiration",  ylab="", cex=1.2)
axis(3, labels=F)
axis(4, labels=F)
mtext(expression(paste(mu, "g CO2-C d"^{-1}, "g"^{-1}, "d.w.")), side=2, las=0, padj=-2.5, cex=.8)

par(mar=c(3,.5,4,5))
accresp<-read.csv("raw_data/accresp_weekly.csv")

plot(accresp$days, accresp$SW.mean, type="l", pch=24, col=colscale[4], xlim=c(0,500), ylim=c(0,.32), lwd=1, main="Accumulated Respiration", yaxt="n")
lines(accresp$days, accresp$AK.mean, col=colscale[1], lwd=2)
lines(accresp$days, accresp$KL.mean, col=colscale[2], lwd=2)
lines(accresp$days, accresp$OS.mean, col=colscale[3], lwd=2)

lines(c(181, 475), c(mean(samples$cons_acc_resp_litC[samples$days==181& samples$type=="AK"]), mean(samples$cons_acc_resp_litC[samples$days==475& samples$type=="AK"])), lty=5, col=colscale[1], lwd=1)
lines(c(181, 475), c(mean(samples$cons_acc_resp_litC[samples$days==181& samples$type=="KL"]), mean(samples$cons_acc_resp_litC[samples$days==475& samples$type=="KL"])), lty=5, col=colscale[2], lwd=1)
lines(c(181, 475), c(mean(samples$cons_acc_resp_litC[samples$days==181& samples$type=="OS"]), mean(samples$cons_acc_resp_litC[samples$days==475& samples$type=="OS"])), lty=5, col=colscale[3], lwd=1)
lines(c(181, 475), c(mean(samples$cons_acc_resp_litC[samples$days==181& samples$type=="SW"]), mean(samples$cons_acc_resp_litC[samples$days==475& samples$type=="SW"])), lty=5, col=colscale[4], lwd=1)

means<-tapply(samples$cons_acc_resp_litC, list(samples$type, samples$days), mean)
se<-tapply(samples$cons_acc_resp_litC_se, list(samples$type, samples$days), mean)
d<-c(0,97,181,475)

plotCI(rep(d[2],4), means[,2], liw=se[,2], uiw=se[,2], cex=0, add=T, gap=0, pt.bg= colscale, pch=pch)
plotCI(rep(d[3],4), means[,3], liw=se[,3], uiw=se[,3], cex=0, add=T, gap=0, pt.bg= colscale, pch=pch)
plotCI(rep(d[4],4), means[,4], liw=se[,4], uiw=se[,4], cex=0, add=T, gap=0, pt.bg= colscale, pch=pch)

axis(2, labels=F)
axis(3, labels=F)
axis(4)

mtext(expression(paste("g CO"[2],"-C g"^{-1}, "litter-C" )), side=4, cex=.8, las=0, padj=2.5)
legend("topleft", typlev, lty=1, col=colscale)

par(mar=c(4,5,3,.5))
timeseries(alldata$DOC_k2SO4, alldata$days, alldata$Litter, pch=pch, pt.bg=colscale, type="o", endsig=T, main="Extractable organic carbon", ylab="", cex=1.2, yaxt="n")
axis(2)
axis(3, labels=F)
axis(4, labels=F)

mtext(expression(paste("mg DOC-C g"^{-1}, " d.w.")), side=2, las=0, padj=-2.5, cex=.8)

par(mar=c(4,.5,3,5))
timeseries(alldata$Phenoloxidase, alldata$days, alldata$Litter, type="o", pch=pch, add=F, pt.bg=colscale, log="y", endsig=T, lwd=1, main="PHENOX", xlab="",  xlim=c(0,550), ylim=c(0.05,5), cex=1.2, yaxt="n", ylab="")
axis(2, labels=F)
axis(3, labels=F)
axis(4)
mtext(expression(paste(mu, "mol min"^{-1}, "g"^{-1},"d.w.")), side=4, cex=.8, las=0, padj=2.7)


par(mar=c(5,5,2,.5))
timeseries(alldata$Cellulase, alldata$days, alldata$Litter, type="o", add=F, pch=pch, pt.bg=colscale, log="y", endsig=T, lwd=1, main="CELL", ylab="", xlab="litter incubation (days)", xlim=c(0,550), ylim=c(0.02,1000), cex=1.2, yaxt="n")
axis(2, axTicks(2), c("0.1", "1.0", "10", "100", "1000"))
legend("bottomright", pch=pch, lty=1, lwd=1, pt.bg=colscale, typlev)
axis(3, labels=F)
axis(4, labels=F)
mtext(expression(paste(mu, "mol min"^{-1}, "g"^{-1}, "d.w.")), side=2, las=0, padj=-2.5, cex=.8)
      
par(mar=c(5,.5,2,5))      
timeseries(alldata$Phenoloxidase/alldata$Cellulase, alldata$days,alldata$Litter, type="o", pch=pch, pt.bg=colscale, log="y", endsig=T, main="PHENOX : CELL", lwd=1,  xlim=c(0,550), cex=1.2, ylab="", ylim=c(0.0005,50), yaxt="n", xlab="litter incubation (days)")
axis(2, labels=F)
axis(3, labels=F)
axis(4, axTicks(2), c("0.001", "0.01", "0.10", "1.00", "10.0"))
mtext(expression("Ratio of potential activities"), side=4, cex=.8, las=0, padj=3.5)

@