<<graphcorr, fig=T, echo=F, results=hide, width=24, height=16>>=
h3.pch<-c(rep(21,5), rep(22,5), rep(23,5), rep(24,5))
h3.col<-c(rep(colscale[1],5),rep(colscale[2],5),rep(colscale[3],5),rep(colscale[4],5))

par()

par(mfrow=c(2,3), cex=2.3, cex.axis=.7, cex.lab=.8)

var1<-alldata$CN_inbal[alldata$days==181]
var2<-alldata$CP_inbal[alldata$days==181]
var3<-alldata$NP_inbal[alldata$days==181]
var4<-hmw.proc$LCI
var5<-hmw.proc$LCdec

var1lab<-"C:N resource / C:N microbial"
var2lab<-"C:P resource / C:P microbial"
var3lab<-"N:P resource / N:P microbial"
var4lab<-"LCI change"
var5lab<-"Lignin decomposition /\n Carbohydrate decomposition"

library('ppcor')

pcor(data.frame(var4, var1, var2, var3))
pcor(data.frame(var4, var1, var2))
pcor(data.frame(var4, var1, var2, var3))
pcor(data.frame(var5, var1, var2))
pcor(data.frame(var5, var1, var2, var3))

pcor.test(var4, var1, var2)
pcor.test(var4, var1, var3)
pcor.test(var4, var2, var1)
pcor.test(var4, var2, var3)
pcor.test(var4, var3, var1)
pcor.test(var4, var3, var2)

pcor.test(var5, var1, var2)
pcor.test(var5, var2, var1)
pcor.test(var5, var1, data.frame(var2, var3))
pcor.test(var5, var2, data.frame(var1, var3))
pcor.test(var5, var3, data.frame(var1, var2))

lm1<-lm(var5 ~ var1)
l1<-
  cor.test(lm1$residuals, var2)

lm2<-lm(var5 ~ var2)
l2<-
  cor.test(lm2$residuals, var3)

lm3<-lm(var5 ~ var3)
l3<-
  cor.test(lm3$residuals, var2)

  lm4<-lm(var4 ~ var3)
l4<-cor.test(lm4$residuals, var2)

cor.test(var5, var3)
l2
lm1
lm2
summary(lm1)


par(mar=c(3,4,2,0.8))
corplot(var1, var4, xlab="", xaxt="n", ylab=var4lab, bg=h3.col, pch=h3.pch)
axis(4, label=F)
axis(1)


par(mar=c(3,2.4,2,2.4))
corplot(var2, var4, xlab="", ylab="", xaxt="n", yaxt="n", bg=h3.col, pch=h3.pch)
axis(1)
axis(2)
axis(4, label=F)
par(mar=c(3,0.8,2,4))
corplot(var3, var4, xlab="", ylab="", xaxt="n", yaxt="n", bg=h3.col, pch=h3.pch)
axis(1)
axis(2)
axis(4)



par(mar=c(5,4,0,.8))
corplot(var1, var5, xlab=var1lab, ylab="", bg=h3.col, pch=h3.pch)
axis(4, label=F)
axis(1)
mtext(var5lab, side=2, cex=1.84, las=0,padj=-2)
#?mtext

par(mar=c(5,2.4,0,2.4))
corplot(var2, var5, xlab=var2lab, ylab="", bg=h3.col, pch=h3.pch)
axis(1)
axis(2)
axis(4, label=F)
par(mar=c(5,0.8,0,4))
corplot(var3, var5, xlab=var3lab, ylab="", bg=h3.col, pch=h3.pch)
axis(1)
axis(2)
axis(4)

@