<<metaprot2, echo=F, results=hide, fig=T, height=18, width=15>>=

metaprot2<-
  rbind(metaprot.red[1:4,T], rep(NA, 26), metaprot.red[5:8,T],rep(NA, 26), metaprot.red[9:12,T],rep(NA, 26), metaprot.red[13:16,T])

names<-c("AK\n 14d", "AK\n 97d", "AK\n 181d", "AK\n 475d", NA, "KL\n 14d", "KL\n 97d", "KL\n 181d", "KL\n 475d", NA, "OS\n 14d", "OS\n 97d", "OS\n 181d", "OS\n 475d", NA, "SW\n 14d", "SW\n 97d", "SW\n 181d", "SW\n 475d")


metaprot2[,22:26]<-metaprot2[,26:22]

taxa<-colnames(metaprot2[,6:26])

taxa[21:17]<- 
  c(expression(paste(alpha, "-Proteobacteria")),
expression(paste(beta, "-Proteobacteria")),
expression(paste(gamma, "-Proteobacteria")),
expression(paste(delta, "-Proteobacteria")),
expression(paste(epsilon, "-Proteobacteria")))

layout(matrix(c(1,2,3,3,4,4),3,2,byrow=T), height=c(.26,.32,.32))
  par(mar=c(4.1,5.1,2.1,.1), cex.axis=.8, cex.lab=1.1, cex=1.2, cex.main=1.2, tck=.01)  

 prot.means<-tapply(f2b$f2b_prot, list(alldata$days, alldata$Litter), mean)
 plot(as.numeric(levels(as.factor(alldata$days))), prot.means[,1], xlim=c(0, 500), ylim=c(0, max(prot.means)), type="o", pch=pch[1], bg=colscale[1], xlab="Litter incubation (days)", ylab="F:B protein abundance ratio", cex=2)
 
 for (i in 2:length(levels(type)))
   {
  lines(as.numeric(levels(as.factor(alldata$days))), prot.means[,i])
  points(as.numeric(levels(as.factor(alldata$days))), prot.means[,i], pch=pch[i], bg=colscale[i], cex=2)
  #, pch=pch[i]], bg=colscale[i])
   }
 legend("topright", levels(type), pch=pch, pt.bg=colscale, lty=1, cex=1, bty="n")
 axis(4, labels=F)
axis(3, labels=F)
#par(xpd=T)
#text(-80, 11.5, labels="A", cex=3)
#par(xpd=F)

par(mar=c(4.1,.1,2.1,5.1))

cond<-is.na(alldata$f2b_qpcr)!=T
timeseries(alldata$f2b_qpcr[cond], alldata$days[cond], alldata$Litter[cond], pch=pch, pt.bg=colscale, xlab="Litter incubation (days)", yaxt="n", xlim=c(0,500), cex=2)
axis(4)
axis(3, labels=F)

axis(2, labels=F)
mtext("F:B DNA ratio (qPCR)", side=4, padj=4, las=0, cex=1.2)


  par(mar=c(5.1, 5.1, 4.1, 10))
  barplot(100*as.matrix(t(metaprot2[,6:13])), main="Fungal community", names.arg=names, cex.names=.7, legend.text=taxa[1:8], args.legend=c(x=28.5, y=70), ylab="Protein abundance (%)", col=1:8)
axis(4, labels=F)


barplot(100*as.matrix(t(metaprot2[,14:26])), main="Bacterial community", names.arg=names, cex.names=.7, legend.text=taxa[9:21], args.legend=c(x=28.5, y=45), ylab="Protein abundance (%)", col=1:13)
axis(4, labels=F)


@